// gen_id_cp_table.mjs -- extract CP_ID_ID from cp_id_tables_multi.h into a
// browser-loadable JS table. The C header stays the single source of truth;
// never edit web/id_cp_table.js by hand. Re-run after any table change.
//   node tools/gen_id_cp_table.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const header = resolve(here, "../mcu/ports/wasm/cp_id_tables_multi.h");
const out = resolve(here, "../web/id_cp_table.js");

const src = readFileSync(header, "utf8");
const m = src.match(/CP_ID_ID\[(\d+)\]\s*=\s*\{([\s\S]*?)\n\};/);
if (!m) throw new Error("CP_ID_ID table not found in " + header);
const entries = [...m[2].matchAll(/\{(0x[0-9a-fA-F]+|\d+)\s*,\s*(\d+)\}/g)]
  .map(x => [parseInt(x[1]), parseInt(x[2])]);
if (entries.length !== parseInt(m[1])) throw new Error(`expected ${m[1]} entries, parsed ${entries.length}`);
const seen = new Set(entries.map(([cp]) => cp));
if (seen.size !== entries.length) throw new Error("duplicate codepoints in CP_ID_ID");

// sanity: the phonemes this whole feature depends on must be present
for (const [cp, want] of [[0x294,109],[0x259,59],[0x25b,61],[0x14b,44],[0x2c8,120]]) {
  const got = entries.find(([c]) => c === cp)?.[1];
  if (got !== want) throw new Error(`cp U+${cp.toString(16)} maps to ${got}, expected ${want}`);
}

const body = entries.map(([cp, id]) => `  [${cp},${id}],`).join("\n");
writeFileSync(out, `\
/* GENERATED by tools/gen_id_cp_table.mjs from mcu/ports/wasm/cp_id_tables_multi.h
 * (CP_ID_ID, slot 4). Do not edit -- re-run the generator instead. */
(function (root) {
  "use strict";
  const MAP = new Map([
${body}
  ]);
  root.SaanoIdTable = Object.freeze({ BOS: 1, PAD: 0, EOS: 2, MAP: MAP });
})(typeof self !== "undefined" ? self : globalThis);
`);
console.log(`wrote ${out}: ${entries.length} codepoints`);
